# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Solicitacao156' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Solicitacao156

  pod 'Firebase/Core'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Facebook'
  pod 'Firebase/Database'
  pod 'GoogleSignIn'
  target 'Solicitacao156Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Solicitacao156UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
